import { FormEvent, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { command, rpc } from "../lib/rpc";
import type { Agent, Project } from "../lib/types";
import "../lib/styles.css";
function NewTask() {
	const [projects, setProjects] = useState<Project[]>([]); const [agents, setAgents] = useState<Agent[]>([]); const [projectId, setProjectId] = useState(""); const [harness, setHarness] = useState(""); const [prompt, setPrompt] = useState(""); const [name, setName] = useState(""); const [error, setError] = useState(""); const [sending, setSending] = useState(false);
	useEffect(() => { void Promise.all([rpc<Project[]>("projects.list"), rpc<{ supported: Agent[] }>("agents.list")]).then(([p, a]) => { setProjects(p); setProjectId(p[0]?.id || ""); setAgents(a.supported || []); setHarness(a.supported?.[0]?.id || ""); }).catch((err: unknown) => setError(err instanceof Error ? err.message : String(err))); }, []);
	const submit = async (event: FormEvent) => { event.preventDefault(); if (!projectId || !prompt.trim() || sending) return; setSending(true); setError(""); try { const session = await rpc<{ id: string }>("sessions.spawn", { projectId, harness: harness || undefined, prompt: prompt.trim(), displayName: name.trim() || undefined }); command("ao.sessions.openWorker", { sessionId: session.id }); } catch (err) { setError(err instanceof Error ? err.message : String(err)); } finally { setSending(false); } };
	return <div className="app form-page"><header className="topbar"><button className="secondary" type="button" onClick={() => command("ao.openBoard")}>← Board</button><span className="brand"><span className="brand-mark" aria-hidden="true" />New task</span></header><h1>Give a worker a clear brief.</h1><p>AO creates an isolated workspace and keeps the feedback loop attached to this task.</p>{error && <div className="error" role="alert">{error}</div>}<form onSubmit={submit}><div className="field"><label htmlFor="project">Project</label><select id="project" required value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Choose a project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></div><div className="field"><label htmlFor="brief">Task brief</label><textarea id="brief" required rows={7} value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="What should the worker deliver? Include the outcome, constraints, and useful context." /></div><div className="field"><label htmlFor="name">Task name <span style={{ color: "var(--muted)", fontWeight: 400 }}>(optional)</span></label><input id="name" value={name} onChange={(event) => setName(event.target.value)} placeholder="e.g. Add rate-limit headers" /></div><div className="field"><label htmlFor="agent">Agent</label><select id="agent" value={harness} onChange={(event) => setHarness(event.target.value)}><option value="">Default agent</option>{agents.map((agent) => <option key={agent.id} value={agent.id}>{agent.label}</option>)}</select></div><div className="form-actions"><button className="secondary" type="button" onClick={() => command("ao.openBoard")}>Cancel</button><button className="primary" disabled={sending || !projectId || !prompt.trim()} type="submit">{sending ? "Starting…" : "Start worker"}</button></div></form></div>;
}
createRoot(document.getElementById("root")!).render(<NewTask />);
